### DISCUSSION TITLE
customized unavailable page and logo is overwritten when new instance is up

### DISCUSSION THREAD

**Discussion by yk-eta** [mozilla/hubs#6052] [Hubs Cloud Questions] [answered]
**Description**
I had replaced the unavailable.html and hubs-cloud-logo.png on s3 asset bucket, but when a new instance is up, it is being replaced.

**To Reproduce**
1. upload customized unavailable page and logo on s3
2. terminate existing instance
3. wait for instance ready

**Expected behavior**
customized unavailable page and logo remain

**Comment by pattersonbl2** [comment]
This probably happens because when the instance is terminated, it rebuilds also reuploading the missing files deleted from s3.  These changes must be done in the admin panel so the configs are passed in the start-up script.

**Comment by yk-eta** [comment]
but admin panel does not having option to update unavailable page and default icon

**Comment by matthewbcool** [comment, marked as answer]
@yk-eta  I used to have a custom unavailable page on my Hubs Cloud a few years ago. 

You have to edit the template itself and point to a different html file.

Of course this is not ideal and it means that you have to remember to update this anytime you update the template. This would be a great feature to have directly in the admin panel.

e.g:

```

CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ErrorCachingMinTTL: 0
          - ErrorCode: 500
            ErrorCachingMinTTL: 0
          - ErrorCode: 502
            ResponsePagePath: !Sub /assets/pages/custom_unavailable.html
            ResponseCode: 502
            ErrorCachingMinTTL: 0
          - ErrorCode: 503
            ResponsePagePath: !Sub /assets/pages/custom_unavailable.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 504
            ResponsePagePath: !Sub /assets/pages/custom_unavailable.html
            ResponseCode: 504
            ErrorCachingMinTTL: 0

 
```
