### ISSUE TITLE
customized unavailable page and logo is overwritten when new instance is up 

### ISSUE THREAD

**Issue by yk-eta** [mozilla/hubs#6011]
**Description**
I had replaced the unavailable.html and hubs-cloud-logo.png on s3 asset bucket, but when a new instance is up, it is being replaced.

**To Reproduce**
1. upload customized unavailable page and logo on s3
2. terminate existing instance
3. wait for instance ready

**Expected behavior**
customized unavailable page and logo remain

**Comment by Pattersonbl2** [comment]
This probably happens because when the instance is terminated, it rebuilds also reuploading the missing files deleted from s3.  These changes must be done in the admin panel so the configs are passed in the start-up script.

**Comment by yk-eta** [comment]
but admin panel does not having option to update unavailable page and default icon

**Comment by matthewbcool** [comment]
@yk-eta  I used to have a custom unavailable page on my Hubs Cloud a few years ago. 

You have to edit the template itself and point to a different html file, otherwise the default one gets recreated over and over.

e.g:

```

CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ErrorCachingMinTTL: 0
          - ErrorCode: 500
            ErrorCachingMinTTL: 0
          - ErrorCode: 502
            ResponsePagePath: !Sub /assets/pages/custom_unavailable.html
            ResponseCode: 502
            ErrorCachingMinTTL: 0
          - ErrorCode: 503
            ResponsePagePath: !Sub /assets/pages/custom_unavailable.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 504
            ResponsePagePath: !Sub /assets/pages/custom_unavailable.html
            ResponseCode: 504
            ErrorCachingMinTTL: 0

 
```
